### PR TITLE
Use wxWidgets 3.2.2, verify checksums, fix flatpak

### PR DESCRIPTION
**Pull request by keesverruijt**
- Build debian-wx32 targets using wxWidgets 3.2.2.1 instead of wx 3.2.1.
- Build flatpak builds with 1 parallel, as I am seeing spurious make errors at 2.
- Allow override of CMAKE_BUILD_TARGET for local builds.

### CODE REVIEW

**Review by leamas — CHANGES_REQUESTED** [review]
Really? I have not seen this as a problem anywhere. Furthermore, the logic obeys the cmake standard variable CMAKE_BUILD_PARALLEL_LEVEL which is the tool to use if needed. You can see examples in other .circleci/config.yml

EDIT: this is about [e5c7808](https://github.com/Rasbats/shipdriver_pi/pull/513/commits/e5c78082220878a2db3c4565a960e2576112198c)

**Review by leamas — CHANGES_REQUESTED** [review]
Frankly, no. Perhaps for a debugging session, but this is way to much code in this context.  If there actually is a bug in the checksumming we should hunt it down before it shows up here. 

The upload script is just not the place for extensive shell programming, we have spent some time to get rid of it. Likewise, it is not the place for a check of wxwidgets version vs actual target, this should be done in cmake code, perhaps in Targets.cmake.

**Review by leamas — CHANGES_REQUESTED** [review]
See my earlier comment: this is not the place, it should be done in cmake code. This also means that there is no need for different cases depending on upload or not.

One more reason is of course local builds...

**Review by leamas — COMMENTED** [review]
This should basically be clean cut. The only problem is a mistake on my side: I created that repo as a public rather than an open-source one. The net effect is that this repo uses some personal download quota I have, and this quota is running low, fast.

I have created a new repo which is open source with the same content alec-leamas/wxwidgets-32. This must be updated, either by you or me. Perhaps easier if you do it, but OTOH it's my bad and I can do it if you prefer that.

**Review by leamas — APPROVED** [review]
Yes.

**Review by leamas — CHANGES_REQUESTED** [review]
No. We build RelWithDebInfo so it's possible to use debug symbols when needed. However, the package is stripped before upload, so this should not change anything w r t the final package. 

If it is not stripped it is a bug which should be reported and fixed, but not this way which makes it complicated to debug locally.

**Review by leamas — APPROVED** [review]

**Comment by Rasbats** [comment]
Some builds failing. @leamas : could you have a look.

**Comment by leamas** [comment]
The builds are probably starting to fail due to the mess I have created see [above](https://github.com/Rasbats/shipdriver_pi/pull/513#pullrequestreview-1379986474). We need to fix the url to ue the new repo...

**Comment by keesverruijt** [comment]
The checksum can't be done in CMake, as it has to be done after `make`. Also, I want to do it this using different code so we don't run into (potentially) the same error as what it is checking. But it can certainly be done outside `upload.sh` if that is what you prefer.

**Comment by leamas** [comment]
> The checksum can't be done in CMake, as it has to be done after make.

well, there are some interesting things happening in cmake/Targets.cmake. For example, take a look at `function (create_finish_script)`

**Pull request merged**
