### PR TITLE
CI: Docker cleanup, travis buildfixes.

### PR DESCRIPTION
**Pull request by leamas**
In this PR:

  - Bugfixes w r t travis builds.
  - Cleanup the docker handling which contained lot's of copy-pasted cruft.

### CODE REVIEW

**Comment by leamas** [comment]
Force-push: Drop test commit from this PR

**Comment by leamas** [comment]
Circle ci build logs [here]8https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/760/workflows/ca04994a-8b76-4592-a580-c8716c58a3ae)

**Comment by Rasbats** [comment]
Looking at circleci checks. The example shows quotes around the build jobs:

[https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml](https://github.com/CircleCI-Public/circleci-demo-workflows/blob/parallel-jobs/.circleci/config.yml)

Our config.yml does not have those quotes. Is this the reason circleci checks are not happening? I am getting web notifications when builds have completed for circleci, but no checks.

**Comment by leamas** [comment]
> Our config.yml does not have those quotes. Is this the reason circleci checks are not happening? 

I suppose anything is possible, but I really doubt it. Several reasons:
  - Using quotes this way only makes sense when one need to force the yaml parser to parse a word as a string rather than a number. However, our keys are like "build-macos" and "build-xenial" which no reasonable parser would parse as numbers.
  - Circleci successfully parses config.yml when  the PR is merged. Why would it parse it differently while still a PR?
  - Our config.yml  file is valid yaml according to [yamllint](http://www.yamllint.com/)
 
In the end,  I still think this is about the github and/or circleci configuration

**Review by Rasbats — APPROVED** [review]

**Comment by Rasbats** [comment]
Tried a few things. Made a branch rule for master but this did not help. Giving up for the time being.

**Comment by Rasbats** [comment]
Not sure if it will have made a difference but I had all repositories selected for circleci checks. Now only ShipDriver is selected.

**Comment by leamas** [comment]
Mike,

As I have said before: I probably need some kind of care. Of course it doesn't  build. In our config.yml there is a filter which makes it build the branches 'master' and 'build'. This does not match the various PR branch names, so ...

Sorry for not seeing this. I will look into a reasonable change. Stay tuned... (BTW: probably best to restore 'all repositories selected for circleci checks')

**Pull request merged**
