### PR TITLE
V3.0 beta4

### PR DESCRIPTION
**Pull request by leamas**
Cherry-picked updates from master, mostly update-templates.

I suggest that if/when you merge this, the tags sd3.0.1-beta2 and sd3.0.1-beta3 are removed since they point to the wrong branch. And then that the v3.0 tip is tagged as sd3.0.1-beta4

As usual, Changelog.md needs an update before the branch is tagged

### CODE REVIEW

**Comment by leamas** [comment]
CirclecCI build logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1255/workflows/3b71ee42-be80-4d6c-8937-1bb71e874dbe)

**Comment by leamas** [comment]
Did I miss the "Comment" button?

Anyway: update-templates is exactly as in previous tests. 

My initial smoke tests looks good. And yours?

**Comment by Rasbats** [comment]
As long as I stay with the CLI everything is fine. If I commit the change to _update-templates_ with Desktop I get into a loop. Is the remote lost? Stay with the CLI for this work :)

**Comment by leamas** [comment]
> Stay with the CLI for this work :)

OK :)

More to document.

**Pull request merged**
