### PR TITLE
Android fixes

### PR DESCRIPTION
**Pull request by leamas**
I have made a torture test of our cmake/ and ci/ directories using the oesenc_pi  plugin. The basic message is that things are stable, there are actually no big changes required to handle also this. With working android builds I have also found the courage to remove the horrible QT_ANDROID hacks in PluǵinLibs.cmake.

This PR:
  - Adds support for OCPN_TARGET_TUPLE, basically a way to override the target-version-arch detection in PluginSetup from the command line.
  - Does some minor cleanup in PluginInstall.
  - Removes all of the QT_ANDRIOD stuff in PluginLibs. In an android build, this file is not used at all, the cross-compilation environment is set up in a separate file.
 
None of these changes should affect existing plugins, it's just a preparation step for upcoming android builds.

### CODE REVIEW

**Comment by leamas** [comment]
Hm... the circleci PR build doesn't seem to kick in (?). My own circle ci logs [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/744/workflows/2753a6d7-89bb-46bf-8b49-389c1cabc9f5)

**Comment by Rasbats** [comment]
Thanks for moving things along. I will have another look at the circleci PR checks.

**Comment by leamas** [comment]
>  I will have another look at the circleci PR checks

Let me know when you are done. I can make a dummy PR just to check.

**Comment by Rasbats** [comment]
Ready... I missed a switch.

**Comment by leamas** [comment]
I tried a new one (#134), but still no joy. "Mystified". Please don't merge it, I have no idea what it is...

**Pull request merged**
