### PR TITLE
cmake: Targets, PluginInstall: flatpak strip fix (#140).

### PR DESCRIPTION
**Pull request by leamas**
As heading says: make sure that Release and MInSizRel builds strips the plugin library file.

Closes: #140

### CODE REVIEW

**Comment by Rasbats** [comment]
Travis check failed:

[https://travis-ci.org/github/Rasbats/shipdriver_pi/builds/758053725](https://travis-ci.org/github/Rasbats/shipdriver_pi/builds/758053725)

**Comment by leamas** [comment]
Ooops... thanks for watching out. Stay tuned for patch (known issue I thought was fixed).

**Comment by Rasbats** [comment]
Not sure where to put this... but latest build for mingw fails

[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/279/workflows/b39d5d55-8ca6-47ae-91ec-8c202287a10c/jobs/2015](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/279/workflows/b39d5d55-8ca6-47ae-91ec-8c202287a10c/jobs/2015)

**Comment by Rasbats** [comment]
Is this needed in circleci-build-mingw.sh :

`# Latest pip 21.0.0 is broken:
python3 -m pip install --force-reinstall pip==20.3.4`

**Comment by leamas** [comment]
I'm on it, know what it is... we are stirring up things atm

**Comment by leamas** [comment]
In short: the python environment situaion is a mess and needs a major overhaul.

**Pull request merged**
