### PR TITLE
Ci update

### PR DESCRIPTION
**Pull request by leamas**
Overhaul of the ci setup:

  - Mingw buildfix
  - Rewrite macos script, clean up homebrew handling, add caching. Build times down from around 6  to two minutes.
  - Rewrite flatpak script, drop the nested Fedora docker builder, add caching. Build times down from around 5 to 2.5 minutes
  - Rewrite the .circleci/config file using anchors, makes the file shorter and easier to maintain 

circleci logs: https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/350/workflows/7075defb-008b-482b-8f0d-d8ab43ed79aa
travis logs: https://travis-ci.com/github/leamas/shipdriver_pi
appveyor logs: https://ci.appveyor.com/project/leamas/shipdriver-pi

### CODE REVIEW

**Comment by leamas** [comment]
Rebased: Fixed a typo in README.md

**Comment by Rasbats** [comment]
Playing with Manjaro Linux this morning due to a question on the forum. OpenCPN Flatpak installed. 
Using the Flatpak tarball I get an error 'undefined symbol _ZTVN4Json10FastWriterE'. 
Json is working fine for the latest build on Windows. 
Do you know of any problem with OpenCPN Flatpak and Json?

A lot of deprecated Json code in ShipDriver. Starting to have a look at updating that.

**Comment by leamas** [comment]
If you have a dependency like Json you must bundle it in the plugin, this is the general contract -- you cannot use any libraries in the host. This is nothing specific for flatpak, but more visible because of  the sandboxing.

So, I don't think the remedy is to update the json code, the fix would be to make sure it is bundled in the plugin. 

Looking at the plugin, I see that it has a separate dynamic library libjsoncpp in the libs/ folder. Seems that the runtime linker does not link to the library. This is a problem, but the root cause here is that we should not have dynamic library at all, it should be statically linked. 

I also see in the flatpakbuild log: Linking CXX shared library ../../../../lib/libjsoncpp.so

We need to fix, that library should be static. I'm on it, stay tuned

**Comment by Rasbats** [comment]
Latest code on my GitHub gets rid of the warnings about deprecated Json code.
Now using Json::CharReaderBuilde and  Json::CharReader. Also Json::CharWriter.
I have got a build running. Will test the Flatpak and see what warnings I get from Manjaro.

**Comment by leamas** [comment]
You will still have this problem. PR under way...

**Comment by Rasbats** [comment]
You are correct. Now working with the PR.

**Pull request merged**
