### PR TITLE
Again: Configuration,  CI: Refactoring and update

### PR DESCRIPTION
**Pull request by leamas**
A new update. Notable changes includes a new workflow like

    $ cmake ..
    $ make tarball

Alternatives includes `make flatpak` and `make pkg`. The latter generates the legacy nsis/img/deb package.

The configuration is also somewhat cleaned up, less project-specific variables. The version is now configured in the `project()` statement.  The former repack-tarball target is gone. 

Other fixes includes a list of components for wxWidgets which was ignored (old pre cmake 3.0 code still lingering) and use of parallel build flags which improves speed considerably on hosts with available cores.

This time, it also builds on windows (the last fix to restoring a code block in PluginCompiler is removed).  Here is also a last-minute fix for a broken cloudsmith-cli version released which breaks the upload.

### CODE REVIEW

**Comment by leamas** [comment]
Builds fine, fails when trying to upload (missing key)

**Comment by leamas** [comment]
Updating version and fixing bugs.

Now, to me this looks like reasonable, alternative way to organize a plugin.

**Comment by Rasbats** [comment]
Will test using this update this morning. Is there any way to include the metadata file in the tarball when building locally? This would avoid using Cloudsmith for hosting the tarball for testing the import.

**Comment by leamas** [comment]
It is included, just use make tarball. There was a bug which named it metadata.xml}, fixed in last push.

**Comment by leamas** [comment]
I'm working in parallel. This code is a never ending story of old samples which have been copied around with too less thought. I find glitches all over the place, but nothing really bad so far.

The wxWidgets bug has been with the plugins code since before cmake 3.0, basically the time of the dinosaurs. The list of libraries was completely ignored, it just happened to be in place anyway. Sigh. Just an example.

**Pull request merged**
