### PR TITLE
Sorry: major update...

### PR DESCRIPTION
**Pull request by leamas**
Here is a major update of the plugin. Some highlights:

   - More cleanup in cmake/, notably PluginPackage. Removoing cruft, simplifying.
   - Clean up the section for plugin-specific setup.
   - Experimental support for tarball checksums, the plugin side of https://github.com/OpenCPN/OpenCPN/pull/2046
   - Experimental support for submitting metadata files using git, see README.git.

The experimental parts should not really affect the plugin unless configured.

Basic tests (importing, installing enabling, menus...) done on Windows, MacOS, Xenial and Flatpak.

### CODE REVIEW

**Comment by leamas** [comment]
If you are curious, enthusiastic and brave you might want to set up the git push tools as described in README.git.  Don't hesitate to ask, the description is not that detailed.

The thing with this is that it makes the PR against OpenCPN/plugins much simpler. Once setup, the basic workflow is.

  - build plugins as usual.
  - When the plugins are uploaded, the metadata is automatically pushed to a branch called 'auto' on your clone of OpenCPN/plugins.
  - When it's time to make a PR. you just merge the auto branch. It will contain many commits, so perhaps using:

          $ git checkout master
          $ get merge --squash auto

    is the way to do it. This will update the shipdriver metadata files to latest version in a single commit. Now, git is sort of flexible, and there are many ways available here

This way, there is no need to download any metadata files from cloudsmith. In fact. the metadata files on cloudsmith could be dropped, they have no purpose.

**Comment by Rasbats** [comment]
Failed at the first hurdle. 
Where should I be looking for the ssh URL? On my fork or at OpenCPN/plugins?
Thanks.
Mike
`
C:\Users\Mike\Documents\GitHub\shipdriver_pi\ci>python new-credentials
Enter ssh URL for ocpn-plugins.xml clone: git@github.com/Rasbats/plugins
Traceback (most recent call last):
  File "new-credentials", line 79, in <module>
    main()
  File "new-credentials", line 61, in main
    user = get_user()
  File "new-credentials", line 45, in get_user
    user = url.split(':')[1]
IndexError: list index out of range

C:\Users\Mike\Documents\GitHub\shipdriver_pi\ci>python new-credentials
Enter ssh URL for ocpn-plugins.xml clone: git@github.com/Rasbats/plugins/ocpn_pl
ugins.xml
Traceback (most recent call last):
  File "new-credentials", line 79, in <module>
    main()
  File "new-credentials", line 61, in main
    user = get_user()
  File "new-credentials", line 45, in get_user
    user = url.split(':')[1]
IndexError: list index out of range

C:\Users\Mike\Documents\GitHub\shipdriver_pi\ci>
`

**Comment by Rasbats** [comment]
I have set up Rasbats/plugins as an SSH enabled repo. Also generated SSH keys for GitHub security.

**Comment by leamas** [comment]
I don't  completely understand where you are in README.git description. 

> Where should I be looking for the ssh URL? On my fork or at OpenCPN/plugins?

Yes. 

The checklist:
  - Run new-credentials using _git@github.com:Rasbats/shipdriver_pi.git_  as ssh url, and a secret password
  - ci/Rasbats.enc and ci/Rasbats.pub are created (by new-credentials). And  and commit them to the git repo.
  - There is a new branch called auto; create it using` git checkout -b auto master`, and push it using `git push origin auto:auto`
  - The ci/Rasbats.pub key is added to https://github.com/Rasbats/plugins as a deployment key with write permissions.
  - The GIT_REPO environment variable is set to _git@github.com:Rasbats/shipdriver_pi.git_ in circleci (and eventually appveyor)
  - The  GIT_KEY_PASSWORD environment variable is set to the same value you fed to new-credentials.

Testing: run a build which uploads a tarball to cloudsmith. You should see that git-push is invoked at the very end. If there are no error messages

**Comment by Rasbats** [comment]
Alec...

There may be a problem with 'new-credentials':
```
C:\Users\Mike\Documents\GitHub\shipdriver_pi\ci>python new-credentials
Enter ssh URL for ocpn-plugins.xml clone: git@github.com:Rasbats/shipdriver_pi.git
Enter password for encrypting new key:
Repeat password:
Traceback (most recent call last):
  File "new-credentials", line 80, in <module>
    main()
  File "new-credentials", line 64, in main
    subprocess.check_call(new_key_cmd)
  File "C:\Python37\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\Python37\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\Python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```
To get this far I had to add 'get_password()' to the script.
```

def main():
    """Indeed: main function."""
    user = get_user()
    get_password()
    new_key_cmd = ['ssh-keygen', '-f', "ci/" + user, '-N', '']
    subprocess.check_call(new_key_cmd)
    print("\nNew key ci/%s  successfully created\n" % user)
    pw = get_password()
    with open("ci/" + user, 'r') as f:
        key = f.read()
```
And the two files it makes are 'leamas.enc' and 'leamas.pub', your keys! Where has 'leamas' come from if the ssh url is git@github.com:Rasbats/shipdriver_pi.git? I did use 'git remote set-url origin .....' to provide an SSH URL for my repo.

**Comment by Rasbats** [comment]
Re-reading ... do I need to fork your repo to test this?

**Comment by leamas** [comment]
> Re-reading ... do I need to fork your repo to test this?

Definitely not.

There seeems to be some windows-specif bug(s) here. Theoretically, python should work  on all platforms, but  that's just theory... I'll see, what I can do, but halloween is upon us :)

**Comment by leamas** [comment]
hm... is the command _ssh-keygen_ available on your current %PATH% ? Seems that it isn't found (?)

**Comment by Rasbats** [comment]
Think I should have installed python rsa. Now testing again.

**Comment by Rasbats** [comment]
The script is failing on Windows whether through python on Windows or through MinGW64 (Git Bash). 

I don't think ssh-keygen is recognised by the Windows OS.

I can run ssh-keygen using MinGW64 standalone. Is there a workaround to create the same keys manually, or a batch file for MinGW64? I have created keys for 'Rasbats' manually with this but they have not worked.

Perhaps _git@github.com:Rasbats/shipdriver_pi.git_ has not been incorporated in the keys.

```
Using repository: **********************************
Using branch: auto
Traceback (most recent call last):
  File "ci/git-push", line 190, in <module>
    main()
  File "ci/git-push", line 169, in main
    private_key_setup(ci, user, password)
  File "ci/git-push", line 61, in private_key_setup
    decrypted = decrypt1(encrypted.encode(), password.encode())
  File "ci/git-push", line 28, in decrypt1
    return cipherFernet(password).decrypt(ciphertext)
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 75, in decrypt
    timestamp, data = Fernet._get_unverified_token_data(token)
  File "/usr/local/lib/python3.7/site-packages/cryptography/fernet.py", line 101, in _get_unverified_token_data
    raise InvalidToken
cryptography.fernet.InvalidToken
```

**Comment by leamas** [comment]
śsh-keygen is recognized if it is installed and in %PATH%. Basically, this seems so far to be about an undocumented dependency on Windows.

On my windows VM ssh-keygen is installed and in %PATH%. It's in   `C:\WINDOWS\System32\OpenSSH`. IIRC this is added when installing git with chocolatey i. e. `choco install git`. Is it acceptable for you to test this?

Did some ad-hoc testing on my windows host. The new-credentials script runs fine for me, besides that it has to be invoked like `python ci\new-credentials`

If you don't want to pull in choco, you could perhaps make a bat file called ssh-keygen.bat which invokes mingw64 with the right options?

Still an alternative would be that you tell me what the command to ruin ssh-keygen using mingw64 is. The script could probe for this possibility and use if it make sense. But this is pretty complicated,  and if we could avoid it would probably be better.

Thoughts?

**Comment by Rasbats** [comment]
My bad mistake. I was invoking the script from 'ci'. Now works ok. Let you know tomorrow how the rest of it goes.

**Comment by leamas** [comment]
Still a bug: the script should be robust enough to work from any place. Will look into that. But great that you can test more!

**Comment by Rasbats** [comment]
Looks like the keys are working but... MacOS example. Other builds are similar:

```
#!/bin/bash --login -eo pipefail
python3 ci/git-push

Using repository: ****************************************
Using branch: auto
Using identity file: /Users/distiller/project/ci/Rasbats
Cloning into 'shipdriver_pi'...
Warning: Permanently added the RSA host key for IP address '140.82.113.3' to the list of known hosts.
remote: Enumerating objects: 376, done.        
remote: Counting objects: 100% (376/376), done.        
remote: Compressing objects: 100% (214/214), done.        
remote: Total 376 (delta 44), reused 310 (delta 42), pack-reused 0              
Receiving objects: 100% (376/376), 474.19 KiB | 5.51 MiB/s, done.               
Resolving deltas: 100% (44/44), done.                                           
Traceback (most recent call last):
  File "ci/git-push", line 190, in <module>
    main()
  File "ci/git-push", line 174, in main
    os.chdir(os.path.join(top, 'plugins'))
FileNotFoundError: [Errno 2] No such file or directory: '/Users/distiller/project/plugins'

Exited with code exit status 1

CircleCI received exit code 1
```
Off to watch a TV drama.

**Comment by leamas** [comment]
Off to bed... Will check this tomorrow. Most likely a bug, a hidden assumption on where the OpenCPN/plugins clone is located... BBL

**Comment by leamas** [comment]
Not quite to bed... seems like the same kind of mistake which made new-credentails fail. Watch for new PR.

**Comment by leamas** [comment]
Ah... I think you are using the ssh url to the shipdriver project, as input to new-credentials and as GIT_REPO,  right? Because silly me told you so. I'm so sorry, lost track myself.

The correct url is the one to the plugins clone i. e. git@github.com:Rasbats/plugins.git. Which means that you need to run new-credentials again, check in the new key, fix the new public key on github and adjust GIT_REPO on circleci. A lot of work, because I did a silly error.

"Blushes"

**Comment by Rasbats** [comment]
I did not understand that the 'auto' branch was for 'plugins' not ShipDriver! Set this up last night and left the build running. This morning I found the xml files in plugins 'auto'. Kudos to the script jockey that you are.

I am using GitHub desktop and it is too easy for me to fixate on one plugin, in this case ShipDriver.

What is the best way to commit the new xml files - direct pull request does not work because of write access to OpenCPN/plugins so I guess it is to update the local master branch and then create the pull request in the legacy way.

**Comment by leamas** [comment]
> I did not understand that the 'auto' branch was for 'plugins' not ShipDriver! 

Well, possible because I gave you the wrong info. Blame me for that!

The idea is that you should have control over the master branch, nothing should happen to it unless you do it yourself. I think I'd do 

        $ git checkout auto
        $ git rebase master
        $ git checkout master
        $ git merge --squash auto

The --squash option lumps all the different commits, one for each build, to a single one. Should keep the master branch somewhat more tidy. The rebase operation should not be necessary, but will pick up possible problems if the shipdriver metadata is changed by other means.

**Comment by leamas** [comment]
And kudos to you for kamikaze testing!  We have found two bugs: that the new-credentials script required you to be in a specific directory, and that new-credential accepted an url which just didn't look sane. PR under way...

**Comment by Rasbats** [comment]
Just tested again with GIT_REPO on appveyor and travis. Both look good. 

Is there any progress with the Android builds? Some of my plugins will have features that will probably not work well with Android. How to select android/non-android? Delete the xml metadata file from the plugins repo as you would for duplicates or those you want to pull?

**Comment by leamas** [comment]
> Is there any progress with the Android builds? 

No :(

**Comment by leamas** [comment]
I have merged your changes to README-git-md. Notes: 

> Should we advise users how to copy/paste the public key as a deployment key on GitHub?

I don't think so. There is a problem when the description becomes too long, for reader and maintainer. Perhaps there is something we can link to? Also, the message when new-credentails is finished could be more explicit.

> Using 'plugins clone' and 'own plugin' I have tried to distinguish between the two repos the user has to work with on GitHub.

Right, good idea. Applied.

> Can GIT_KEY_PASSWORD and GIT_REPO environment variables be entered on the builder so that all plugins from a user can use them if required?

Circleci has a 'context' mechanism which targets exactly this. I havn't really looked into it, though.

Will make a PR later.

**Pull request merged**
