### PR TITLE
Drone: Adding new builder drone.io, dropping travis.

### PR DESCRIPTION
**Pull request by leamas**
This PR is basically just to announce what's going on. Please don't merge yet, here is more work to do.

One thing is updating the wiki. Could you look into this, just adding the drone.io builder for now? Compared to the others it much less complex. It might also make sense if you created an account there.

drone.io might survice as an open-source alternative for some time if I understand this correct (knock, knock...). It seems fast, and has native arm support. However, buildiing flatpak there looks problematic, I have filed ticket but i doubt there is a solution. Still, it's definitely useful. It's docker-centric, and all those things which runs in docker becomes simpler and faster.

### CODE REVIEW

**Comment by leamas** [comment]
Drone build logs: https://cloud.drone.io/leamas/shipdriver_pi/56/2/2

**Comment by leamas** [comment]
Moved last raspbian, slow build from circleci to drone.

Drone logs: https://cloud.drone.io/leamas/shipdriver_pi/64/

**Comment by Rasbats** [comment]
Good timing. I have just set up my R Pi to test builds for Raspberry Pi OS (based on Debian buster).

**Comment by leamas** [comment]
Oops... you merged it. ok :)

Could you possibly update the docs at the wiki?

**Comment by leamas** [comment]
Also, now when it's merged: You need to arrange for an account at cloud.drone.io so the  thing actually is built also on master branch changes...

**Comment by Rasbats** [comment]
Just going to test the Raspberry build. Wiki tomorrow. 
> so the thing actually is built also on master branch 
The build happened and the result in in Cloudsmith. Is something else needed?

**Comment by leamas** [comment]
> The build happened and the result in in Cloudsmith. Is something else needed?

No. But then there is the documentation (the wiki...)

**Comment by Rasbats** [comment]
Ok... Drop travis.yml, add drone.yml. etc, etc. Tomorrow.
BTW the build works fine on my R Pi. No environment variables for drone.io? So how do we get the build into master?

**Comment by Rasbats** [comment]
Is this already taken care of by CircleCI?

**Comment by Rasbats** [comment]
Too lazy to look at scripts!

**Comment by leamas** [comment]
As a starter, you'll probably have to look at .drone.yml. That's the starting point.

Nothing from circleci is exported to drone.io.

The builder at drone.io needs the same environment variables as other builders. They are easy to set up (called "secrets") in a slimmed down, focused UI. I don't think you should have any difficulties, but don't hesitate to drop a note if you have.

The two build scripts are basically the same as on circleci, with the difference that there is no VM running the docker instance -- drone.io runs the docker instance directly. This makes them smaller and easier to handle. You should not have to look into them from the beginning.

**Comment by Rasbats** [comment]
Wiki is done (needs checking).

**Comment by leamas** [comment]
Looks great! I have nothing to add.

(well, I need to add a new page about poor fellows like me which don't have hard-coded repository names in the code. We must define OCPN_STABLE_REPO and friends... :( )

**Comment by leamas** [comment]
Off-topic: I filed a bug at OpenCPN (https://github.com/OpenCPN/OpenCPN/issues/2178) . This is one of the things I need to handle, but I'm running out of time (and, to some extent, also out of steam).

Dave has merged "our" setup in github.com/bdbcat/oesenc_pi/. This  basically means that what we have accomplished (don't underestimate your role!) has survived a more thorough review. We are doing some things right, obviously.

**Pull request merged**
