### PR TITLE
Update-templates fixes

### PR DESCRIPTION
**Pull request by leamas**
- Fix a options string typo
- Make sure not all tags are downloaded from shipdriver
- Handle missing shipdriver remote when doing -l

### CODE REVIEW

**Comment by leamas** [comment]
I have tested this using the -T option. The real testing without this cannot be done until it's merged.

**Comment by leamas** [comment]
Did some more testing. The update (really: downgrade) to sd3.0.1-beta1 creates a mess. Could you tag current state as  _sd3.0.1-beta2_ so we can go on?

**Comment by Rasbats** [comment]
>Could you tag current state as sd3.0.1-beta2 so we can go on?

Done.

**Comment by Rasbats** [comment]
The update makes 8 commits. Could these be reduced to just one? Make it easier to revert.

Notice the script gets the latest template with -l and then we commit this.

But when the script is run again (sd3.0.1-beta1) we have to make a further commit before using the script again to add the changes.

**Comment by leamas** [comment]
> The update makes 8 commits. Could these be reduced to just one? Make it easier to revert.

You mean the update from sd3.0.1-beta1 to sd3.0.1-beta2 ?

**Comment by leamas** [comment]
We should not revert things unless we really have to. Nothing to plan for, really.

We are actually looking for making _update-templates sd3.0.2_ work.  The betas are steps on that road.

Making a quick smoketest with _update-templates sd3.0.2-beta2_ all looks good to me. What happens when you test?

**Comment by Rasbats** [comment]
>You mean the update from sd3.0.1-beta1 to sd3.0.1-beta2 ?

No ... when using update-templates for a non-managed plugin.

**Comment by Rasbats** [comment]
```
Mike@vostro-64 MINGW64 ~
$ cd /c/Users/Mike/Documents/GitHub/otidalroute_pi

Mike@vostro-64 MINGW64 ~/Documents/GitHub/otidalroute_pi (master)
$ ./update-templates sd3.0.1-beta2
Removing existing shipdriver remote.
Adding new shipdriver remote
```
Hangs when adding the remote. This also happened with `-l`

Not found with the previous version.

**Comment by Rasbats** [comment]
Now done the business. May be my Internet speed today. It has been flaky.

**Comment by leamas** [comment]
Ah... see what you mean.  However, merging them to one commit is still IMHO not a good idea.

First: assume you start at deadbee before doing the update. You can still undo it in one command: `git reset --hard deadbee`, assuming nothing is pushed. This is actually much cleaner than doing revert.

Second: having it as separate commits makes it IMHO much easier to review and perhaps amend. Might be wrong, of course.

**Comment by leamas** [comment]
> Now done the business. May be my Internet speed today. It has been flaky.

Everything OK, besides your ISP?  Or?

**Comment by Rasbats** [comment]
Testing some more. I like the fact that less commits of update-templates is needed. The script just gets on with the work.

At the moment things look good.

**Comment by leamas** [comment]
We *will* need to update update-templates later. Take for example next major release (3.1?) which most likely will contain a git submodule.  This is nothing the current version of update-templates knows about, so an update will be needed.  More generally, it's hard to know the future.

OTOH, most plugins should be bootstrapped at that point, update-templates does already exist so it's then just about running it, commit the update and run again.

**Pull request merged**
