### PR TITLE
Arm64: Add arm64 builds on circleci builder.

### PR DESCRIPTION
**Pull request by leamas**
Add flatpak arm64 builds on circleci arm64 builders. This means we can retire the builds on my personal hardware accessible using Github Actions. The builds are basically the same as done by the Github Actions builder.

Drop github flatpak builds.

The travis.yml contains hooks for adding  flatpak builds later as an alternative to circleci.

See: https://github.com/OpenCPN/OpenCPN/issues/2178

### CODE REVIEW

**Comment by Rasbats** [comment]
Getting workflow failed.

[https://github.com/Rasbats/shipdriver_pi/actions/runs/810626694](https://github.com/Rasbats/shipdriver_pi/actions/runs/810626694)

Is something else needed to remove the old workflow using your personal hardware?

**Comment by leamas** [comment]
I did not change anything... could you perhaps just disable Actions in the Github UI?

**Comment by leamas** [comment]
ARRGH: I missed to remove .github/actions/shipdriver.yml (!) Could you please just remove it and make a new run?

**Comment by leamas** [comment]
All set... thanks!

**Comment by Rasbats** [comment]
Testing on arm64 RPi: Latest ShipDriver 64 bit build shows as an incompatible plugin.
Looking at the metadata.xml file... target-arch shows as arm64. Previously this was aarch64, which loads without error on the latest amd64 OpenCPN flatpak beta. 

Does something need to change in GetArch.cmake?

**Comment by Rasbats** [comment]
Changed the target and target-arch in metadata.xml to show aarch64 and the import worked!

**Comment by leamas** [comment]
> target-arch shows as arm64.

This is a plain bug. As you say, it should be flatpak-aarch64. I'll look into it, probably a point patch I did which is lost somewhere.

**Comment by leamas** [comment]
Again: Thanks!  A really good catch!

**Pull request merged**
