### PR TITLE
Update android builds

### PR DESCRIPTION
**Pull request by leamas**
- Update the deprecated circleci android images.
- Update the  mega blob used for linking the plugins to API 1.18

### CODE REVIEW

**Comment by Rasbats** [comment]
Android builds failed ???

**Comment by leamas** [comment]
Dont for me. Link?

**Comment by Rasbats** [comment]
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/998/workflows/cabd16e4-bda5-4bcb-95b9-8de4e3e322a1](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/998/workflows/cabd16e4-bda5-4bcb-95b9-8de4e3e322a1)

**Comment by leamas** [comment]
Hm... it seems that the download from github takes forever some reason. When I tried locally, there was even a checksum error after a longgggg time. 

Successful builds for same commit [here] (https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1870/workflows/7a179f91-c7e0-4bc2-8835-556459bd61a3)

Let's see if this sorts out when github resumes to normal download speeds. 

Yes, it would be better if we got some feedback while downloading. I do use SHOW_PROGRESS  to the cmake `file(DOWNLOAD...) command, but to no avail.

**Comment by leamas** [comment]
Right now it seems that github us up again. Could you please try to rebuild?

**Comment by Rasbats** [comment]
Rerun from failed did not work:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/998/workflows/385b0965-ad5f-4c7e-97b6-4538418ec17d](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/998/workflows/385b0965-ad5f-4c7e-97b6-4538418ec17d)

arm64 failed, armhf stuck in a loop. I will try a rerun from the start.

**Comment by leamas** [comment]
This is still about downloading from github. There is basically no hurry then, let's wait to tomorrow or so.

**Comment by leamas** [comment]
The github issue seems to be resolved: https://www.githubstatus.com/incidents/frdfpnnt85s8

Successful rebuild [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/1871/workflows/e0700f24-0624-496e-aba8-0b224e0d5056)

If you also can rebuild I guess we can try to close it again :)

**Comment by leamas** [comment]
Oops, sorry. This discussion now lives in #551

**Pull request merged**
