### PR TITLE
Review: please don't merge this, but...

### PR DESCRIPTION
**Pull request by leamas**
... I have had a long-time idea about refactoring CMakeLists into two parts, one of which generic and the other containing the plugin-specific parts. I have hesitated, mostly because not being clear about what "worts case" scenarios for plugin configuration are.

However, even Dave's doesn't look that bad. So, here is the idea: we split CMakeLists into two parts: One which is generic (and thus can be updated by update-templates), and a new file CMakePlugin.cmake  which contains the plugin-specific stuff.

The advantages would basically be to simplify maintenance. 

This is a big change,  perhaps too big to make, perhaps big enough to be postponed for now i. e., to after some kind of 3.0 release. Or, it's perhaps just a bad idea.

Thoughts?

### CODE REVIEW

**Comment by leamas** [comment]
Rebased to current master.

**Comment by Rasbats** [comment]
Yes ... I like this. Need to update 16 plugins. Now would be a good time before starting on that. Maybe move to v3 with this update now. I can announce the Android build after publication.
One addition to _CMakeLists.txt_ is needed. _libs_ needs _api-17_. This is because JavaScript_pi is using that api already.
The contents are here:
[https://github.com/Rasbats/JavaScript_pi](https://github.com/Rasbats/JavaScript_pi)
I can do that update after the PR is in.

**Comment by leamas** [comment]
> . Need to update 16 plugins. 

... which means it time to use the update-templates script. It's actually a fast and reliable way to do it after learning about it.

> Now would be a good time before starting on that. Maybe move to v3 with this update now. 

Yes. I have a PR in the oven, stay tuned. Also, please consider #276 before making a first beta/rc release.

**Comment by Rasbats** [comment]
api-17 added. 
Version now sd2.9
Keys moved to _build-deps_.

**Comment by Rasbats** [comment]
Now a conflict has appeared due to` include(CMakePlugin.cmake)`.

**Comment by leamas** [comment]
I have rebased locally and is running test builds. stay tuned.

**Comment by leamas** [comment]
Having problems with MacOS after rebasing. Need to to a bisect to find the error, will take some time. Shall I make a PR with what I have for now, with a follow-up for MacOS later? Or do you want to wait?

**Comment by Rasbats** [comment]
Go for the PR now.

**Pull request merged**
