### PR TITLE
#312: Move temporaries to project cache directory.

### PR DESCRIPTION
**Pull request by leamas**
Make flatpak, windows and since earlier Android builds us a common cache directory for downloads and other state. This means that the cache persists even if the build directory is cleared and also avoids cluttering for example c:/ top directory with various downloads.

Might be other things to handle before closing #312, but this should be a good starter. Builds on all hosts and does not cause any changed behaviour in local builds.

### CODE REVIEW

**Comment by Rasbats** [comment]
Checks fail. Is this because previous PR have not been accepted yet?

**Comment by leamas** [comment]
Probably not. I'll look into it, thanks for heads up!

**Comment by leamas** [comment]
fixed. This is probably independent of #309, so they could be applied in any order. Will rebase if necessary after merging any of these.

**Comment by leamas** [comment]
Need to review the situation after merging PRs and test more. Keeping open

**Pull request merged**
