### PR TITLE
Mingw

### PR DESCRIPTION
**Pull request by leamas**
OK, here is the mingw build, two scripts merged, updated fedora builder i. e., it should work  a little longer.

### CODE REVIEW

**Comment by Rasbats** [comment]
For the other plugins the Cloudsmith API key is enough for Travis but not these builds.

**Comment by leamas** [comment]
"these" being mingw, or?

**Comment by leamas** [comment]
When I look at the message in  the failing mingw build it seems that CLOUDSMITH_API_KEY is missing.  Are you sure it's there? 

We should add a status printout on the API key, PR under way

**Comment by leamas** [comment]
hm... PR  #26 is submitted, and is good anyway. But I can actually reproduce the problem. Let's see what's in this can of worms...

**Pull request merged**
