### PR TITLE
Source code formatting

### PR DESCRIPTION
**Pull request by leamas**
This is an attempt to establish a uniform source code formatting. By necessity, this requires rewriting all source files and should not be merged lightly. 

That said, we need to address this issue, and this is perhaps the proper time to do it (?).

The basic tool is clang-format, part of the llvm project, which is readily available on all platforms.

### CODE REVIEW

**Comment by leamas** [comment]
circleci build logs: https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/642/workflows/3c2a59e2-9678-4d6d-b366-ad1c7c397fb4

**Comment by Rasbats** [comment]
This is good but I am going to leave it for a day or two. I am working on the documentation and have the outline for this in place. Intend sending you a copy before going live.

**Comment by leamas** [comment]
Right, that is the proper priorities.

**Comment by leamas** [comment]
Please don't send me a copy, just commit and push it so I can review and perhaps make a PR. You could make it happen on a separate branch if you don want to expose it until it's ready.

**Comment by Rasbats** [comment]
It all went well until I ran into the permission denied problem. Is there a script for Windows that will give the build scripts permission to execute.
[https://github.com/Rasbats/managed/wiki/Cloud-Service-Changes](url)

**Comment by Rasbats** [comment]
[](https://github.com/Rasbats/managed/wiki/)

**Comment by leamas** [comment]
Rebased to current master

**Comment by Rasbats** [comment]
About time I did this!

**Comment by Rasbats** [comment]
Did you see the issue with mingw?   **Adding a beta version to OpenCPN/plugins beta branch #108**

**Comment by leamas** [comment]
mingw: Nothing wrong with shipdriver or your other plugins, this is a problem in the plugins projects's beta branch: https://github.com/OpenCPN/plugins/issues/313

**Pull request merged**
