### PR TITLE
improve local-build.rc doc

### PR DESCRIPTION
**Pull request by rgleason**

### CODE REVIEW

**Comment by Rasbats** [comment]
@leamas : Never use this. Does it look ok?

**Comment by rgleason** [comment]
Rasbats, since you don't use it, how do you automatically push to opencpn/plugins?
Also since you don't use this, I am wondering now, what it is used for specifically?

**Comment by leamas** [comment]
No, this  is not professional. Needs a better phrasing without caps lock.

**Comment by rgleason** [comment]
So you have no problem putting landmines in the template that will blow up an entire setup, and not bother to alert your users? In my opinion this is insane.

**Comment by rgleason** [comment]
Additionally there has been little explanation for the existence of this file to begin with. Rasbats doesn't use it and he deploys automatically.

**Comment by rgleason** [comment]
I think it should just be removed.

**Comment by rgleason** [comment]
Why? Because "Import Plugin is much simpler for testing and there is practically no use for it.

**Comment by rgleason** [comment]
You ask for a PR and even insist on it and then call it "not professional"?
Why bother?

**Comment by Rasbats** [comment]
@leamas : The scripts directory is a recent addition. Probably useful for your work but is it needed in this repo?

**Comment by leamas** [comment]
It's a new addition triggered by the situation when CircleCI was unavailable. It then became clear that CCI is a single point of failure. 

The scripts directory makes it possible to not just build but also push to Cloudsmith and Github directly. This is intended to be useful  if/when CCI is unavailable and also as a debugging tool. I think this will become useful over time, but this is the first iteration... 

IMHO, we can for now just let it sit there. The  documentation needs to clarify it's role, though.

**Comment by leamas** [comment]
> Additionally there has been little explanation for the existence of this file to begin with.

Agreed

**Comment by leamas** [comment]
> You ask for a PR and even insist on it and then call it "not professional"?

Well, long sentences is upper case just does not meet best practice documentation standards. Nor does repeating the same thing again and again.

Still, I get your point and it was valuable input for #369. The role of a patch or a PR is not always that it should be merged, it can also be to phrase intentions in a more concrete way. Which you certainly did here.

**Pull request closed without merging**
