### PR TITLE
Handle libraries as a git submodule (#296)

### PR DESCRIPTION
**Pull request by leamas**
As heading says: instead of hard to maintain local copies of all libraries gather them in  a common submodule.

Operations to create, update, modify locally and remove are described in the [README](https://github.com/leamas/opencpn-libs/blob/main/README.md).

The upside with this approach is maintenance, we can maintain a common set of libraries in one place instead a vast amount of independent copies. The downside is the added complexity. 

Let's see where it goes...

EDIT: Nothing stops a plugin from   having  "local" libraries maintained locally as before in libs/. This is what I anticipate will happen in some plugins which have non-reusable libraries like oesenc and o-charts.

### CODE REVIEW

**Comment by leamas** [comment]
OK. Now let's see if there are more bugs, I will try to use it again on some hard plugins i. e., hard part first.

**Comment by Rasbats** [comment]
I have raised a ticket with circleci for the MacOS problem.

**Comment by leamas** [comment]
So have I...

**Comment by Rasbats** [comment]
Use case:
I have been working on otcurrent_pi, trying to make an Android version. At the moment I can work with the clone. 
Build locally to create a .dll and add this to OpenCPN plugins to test. A tarball has already been installed so I am just changing the .dll.
Oh dear ... failed agin. I open the Visual Studio solution. Make changes. It compiles. Test on OpenCPN.
Close the solution. Commit to the repo to make a ci build.
Repeat many times.
What we have with this commit are libs online. This will require downloading the opencpn-libs each time a change is made locally. 
How can this be made to work for local builds?

**Comment by Rasbats** [comment]
Looks like the tickets have had a result. Now in _circleci-build-macos.h_ do I set everything to 10.10?

**Comment by leamas** [comment]
> How can this be made to work for local builds?

Here is something I just don't understand. When it comes to local builds, I just init the submodule and then basically forgets about it, it just works.

Wait, did I document that? Did you do `git submodule update --init opencpn-libs` in your local clone?

**Comment by leamas** [comment]
It is in ci/circleci-build-macos.sh where you have the lines
```
cmake \
  -DCMAKE_BUILD_TYPE=Release \
  -DwxWidgets_CONFIG_EXECUTABLE=/tmp/wx315_opencpn50_macos1010/bin/wx-config \
  -DwxWidgets_CONFIG_OPTIONS="--prefix=/tmp/wx315_opencpn50_macos1010" \
  -DCMAKE_INSTALL_PREFIX= \
  -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 \
  ..

```

i. e., it's already fixed.

**Pull request merged**
