### PR TITLE
cmake: Clean up messy targets definitions (#95)

### PR DESCRIPTION
**Pull request by leamas**
Use a cmake batch file instead of trllions of targets to get a sequential flow.

Closes: #95

### CODE REVIEW

**Comment by leamas** [comment]
hm... yet another windows problem not visible in my builds. Please don't merge, BBL.

**Comment by leamas** [comment]
Clean-up and bugfixes.  Circleci logs  [here](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/633/workflows/5f4e3f39-f75b-442e-a97b-19dc5b2383dd)

I suggest that this is merged. After all it builds on appveyour, and I have found and fixed some bugs. Please check if there are any other issues when building locally on windows.

**Comment by Rasbats** [comment]
The wxWidgets problem is still with us. In the path and referenced by the bat file but not found.

```
-- Found OpenGL...
  --     Lib: opengl32glu32
  --     Include:
  CMake Error at C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:165 (message):
  -- Configuring incomplete, errors occurred!
  See also "C:/project/opencpn/shipdriver_pi/build/CMakeFiles/CMakeOutput.log".
    Could NOT find wxWidgets (missing: base core net xml html adv gl)
  Call Stack (most recent call first):
    C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindPackageHandleStandardArgs.cmake:458 (_FPHSA_FAILURE_MESSAGE)
    C:/Program Files (x86)/CMake/share/cmake-3.18/Modules/FindwxWidgets.cmake:1008 (find_package_handle_standard_args)
    cmake/PluginLibs.cmake:25 (find_package)
    CMakeLists.txt:131 (include)


C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: The command "setlocal [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: cmake -DCMAKE_INSTAL
L_PREFIX=C:/project/opencpn/shipdriver_pi/build/app/files -DBUILD_TYPE:STRING=tarball C:/project/opencpn/shipdriver_pi/build [C:\project\opencpn\shipdriver_pi
\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq
0 goto :cmEnd [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmEnd [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: endlocal & call :cmErrorLevel %errorlevel% & goto :cmDone [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmErrorLevel [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: exit /b %1 [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :cmDone [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: if %errorlevel% neq0 goto :VCEnd [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Microsoft.CppCommon.targets(138,5): error MSB3073: :VCEnd" exited with code 1. [C:\project\opencpn\shipdriver_pi\build\tarball-conf.vcxproj]
C:\project\opencpn\shipdriver_pi\build>
```

**Comment by leamas** [comment]
Yes... but the message is simple: you need wxWidgets to build the plugin, it's a dependency and has always been.

The recipe to install it is in appveyour.yml, it's about downloading and unpacking an archive.

A windows bat file installing all deps in the same way as appveyor does wouldn't be wrong. However, it should check if things are already in place before doing the installs.

**Comment by Rasbats** [comment]
The reason for wanting the batch file to work is to enable editing of the source code with VS and being able to see the result of that change without CI. Needs testing on Linux as well. I use CodeBlocks for edits there.

**Comment by leamas** [comment]
CodeBlocks?! I'm lost...

Anyway, I don't see anything wrong in the cmake scripts here. build scripts more or less always presumes that dependencies are installed.  This is easy on LInux, which uses packaged deps. Not so easy on windows. As I said, a separate .bat file like "windows-deps.bat"  (and a macos-deps.sh) could be motivated. but then more complicated code to maintain.

The simple alternative, and first step in any case, would be to document the steps necessary to install the windows build deps.

**Comment by Rasbats** [comment]
I think I have seen the problem. CMakeCache.txt is telling me that it is looking in the directory "C:/wxWidgets-3.1.2/lib/vc_lib". It should be looking in 'C:/wxWidgets-3.1.2/lib/vc_dll'. If I download wxWidgets from OpenCPN I get the folder '/vc_dll'.

The batch file is using '/vc_dll' so where is '/vc_lib' coming from?

**Comment by leamas** [comment]
The appveyor.yml  has
```
  - set WXWIN=C:\wxWidgets-3.1.2
  - set wxWidgets_ROOT_DIR=%WXWIN%
  - set wxWidgets_LIB_DIR=%WXWIN%\lib\vc_dll
```
so it seems to be about the environment.  FindWxWidgets is not [documented](https://cmake.org/cmake/help/latest/module/FindwxWidgets.html) that well, many options and variables which are used requires going to the sources.

What happens if you set  _wxWidgets_LIB_DIR_ to the correct value?

**Comment by Rasbats** [comment]
>What happens if you set wxWidgets_LIB_DIR to the correct value?

No joy. 
This looks as if it is involved:
[https://github.com/microsoft/vcpkg/issues/4756](url)

**Comment by Rasbats** [comment]
Remembered some problems with JavaScript_pi and solved it with another way of referencing wxWidgets.

[PluginLibs.txt](https://github.com/Rasbats/shipdriver_pi/files/5689612/PluginLibs.txt)

Probably a total hack but ShipDriver builds locally. Could you work with something like this for github/ci?

**Comment by leamas** [comment]
We should avoid local hacks, if possible. Reading the bug, the cmake people claims to have an updated FindwxWidgets.cmake at https://gitlab.com/kicad/code/kicad/-/raw/master/CMakeModules/FindwxWidgets.cmake.  You could try to drop it as-is in the cmake/ directory, it will then override the system-wide copy

**Comment by Rasbats** [comment]
Yes... I tried that but then FindwxWidgets.cmake is looking for further CMake modules.  
I am going to push the fix to github and see what effect it has on CI.

**Comment by leamas** [comment]
Ah, right. That's how it ends, been there, done that.

Messy, this.  Walking away to get food, cables and what not in city center.

**Comment by Rasbats** [comment]
ci works!

**Comment by leamas** [comment]
Sorry for bringing  bad news to the party... but I filed a note on your commit. Please let me know if you don't find it.

BTW: You might consider enhancing your commit messages a little. In this case, it would make a lot of sense to add a link to the bug in the code as a comment and/or in the commit message (please let me know if you are'nt interested in these kinds of comments)

**Pull request merged**
