### PR TITLE
Edits: upstreamed changes from UKTides

### PR DESCRIPTION
**Pull request by leamas**
Review files in need of change when used in other plugins, upstreamed from UKTides. 

See: https://github.com/Rasbats/UKTides_pi/pull/9

### CODE REVIEW

**Comment by Rasbats** [comment]
Problem with the flatpak build:

```
+ flatpak install --user -y flathub org.opencpn.OpenCPN
+ flatpak install --user -y flathub org.freedesktop.Sdk//18.08
+ sed -i '/^runtime-version/s/:.*/: stable/' flatpak/flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
sed: can't read flatpak/flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml: No such file or directory
```
Too many flatpaks somewhere?

**Comment by leamas** [comment]
Indeed. Stay tuned...

**Comment by leamas** [comment]
Can you apply this directly, without a PR?

```
diff --git a/ci/circleci-build-flatpak.sh b/ci/circleci-build-flatpak.sh
index 11ccd89..02c0afd 100755
--- a/ci/circleci-build-flatpak.sh
+++ b/ci/circleci-build-flatpak.sh
@@ -11,7 +11,7 @@
 #
 
 set -xe
-MANIFEST=flatpak/org.opencpn.OpenCPN.Plugin.shipdriver.yaml
+MANIFEST=org.opencpn.OpenCPN.Plugin.shipdriver.yaml

```

**Comment by Rasbats** [comment]
Yes, I will do that one.

**Pull request merged**
