### PR TITLE
build: Add patch level to version (#19).

### PR DESCRIPTION
**Pull request by leamas**
As discussed in #19, a plain bugfix. Please rebase when merging.

### CODE REVIEW

**Comment by Rasbats** [comment]
Ok... I am now going to use the present code to remove the managed_plugin bits.

**Comment by leamas** [comment]
Sounds great to me. Perhaps you should also setup the environment variables in the travis builder before you merge. Would be good to have a green OK from the CI build...

**Comment by Rasbats** [comment]
v2.4.9 now built. I think there was a redundant EV in Travis that caused the issue. Now removed. All the other plugins use only the CloudSmith API key. Naming works much better on the Mac. 
Your builds don't include some OS! The pic shows the ones built with frontend2.
workflows

Can the missing frontend2 scripts just be added to the repo?

**Comment by leamas** [comment]
If you want them I can certainly fix it. However, I'll use my own scripts.

That said, we cant build focal or bionic-gtlk3 until  #20 is resolved.  In which order shall we proceed? Adding the builds we can make, or  fix the gtk3 build first?

**Comment by Rasbats** [comment]
gtk3 first please.

**Comment by leamas** [comment]
OK... I need to do some other things first... stay tuned.

**Pull request merged**
