### PR TITLE
Macos v2

### PR DESCRIPTION
**Pull request by leamas**
I still hesitate to use Dave's completely undocumented tarball. Once it becomes documented things might change.

This version rebuilds wxWidgets form source. This takes a long time (~25 minutes), so to keep build times sane I have also re-enabled the caching. For me, all builds except the first now builds in about 3 minutes which is much faster than the existing macos builds.

Of course, this needs testing to see  that the  compilation flags I got from Dave actually matches what's in OpenCPN i.e., that the tarballs generated this way can be loaded into current OpenCPN

### CODE REVIEW

**Comment by Rasbats** [comment]
Thanks. Will test. I have tried a number of things to fix the missing symbol problem. No luck at all.

**Comment by leamas** [comment]
OK, thanks.  I added some notes in the very end of INSTALL.md which might be useful.

**Comment by Rasbats** [comment]
Ok ... works fine with todays MacOS build of OpenCPN.

**Comment by leamas** [comment]
Great to hear. Sorry for the first painful build you had to do. The upcoming ones should be fast, though.

**Pull request merged**
