### PR TITLE
Metadata fixes

### PR DESCRIPTION
**Pull request by leamas**
This was mostly a new and interesting (well..) issue with flatpak. Now it seems to work, at least for me  i. e., flatpak.

### CODE REVIEW

**Comment by leamas** [comment]
Built artofacts: https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/

**Comment by Rasbats** [comment]
Thanks. This seems to have fixed Windows. I will take a look at other OS tomorrow. Thanks for your patience with this.

**Comment by leamas** [comment]
>  Thanks for your patience with this.

Same to you!

--a

**Comment by leamas** [comment]
Hi,

>  I will take a look at other OS tomorrow

Not to rush anything, but I'm of course a little curious how things are from your point of view after some sleep, more testing etc.

**Pull request merged**
