### PR TITLE
Cleanup: Merge duplicated ci scripts, remove unused build deps

### LINKED ISSUE #115: ci: Lot's of useless build deps.
The CI files contains a lot of useless build dependencies, originally just copied from main OpenCPN. These should be trimmed down to what's actually used to avoid needless build time and also instability caused by unavailable or changed unused packages.

### PR DESCRIPTION
**Pull request by leamas**
As heading says.

Closes: #114 
Closes #115

### CODE REVIEW

**Comment by Rasbats** [comment]
Circleci failed for the Mac build
[(https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/252/workflows/459eda4b-6268-4e96-8355-28ed9b1b6706/jobs/1760)](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/252/workflows/459eda4b-6268-4e96-8355-28ed9b1b6706/jobs/1760)
Appveyor also failed:
[https://ci.appveyor.com/project/Rasbats/shipdriver-pi](https://ci.appveyor.com/project/Rasbats/shipdriver-pi)

I will leave as is. Working with Ubuntu Focal at the moment.

**Comment by leamas** [comment]
Seems like unrelated network errors, download failures from download.opencpn.org, both MacOS and appveyor

Working builds for same commit: [appveyor](https://ci.appveyor.com/project/leamas/shipdriver-pi/builds/37151581), [macos](https://app.circleci.com/pipelines/github/leamas/shipdriver_pi/688/workflows/73dfb9b8-f218-4cf9-be72-4ff3b6ae215c)

**Comment by Rasbats** [comment]
I will try another build to see if it now works.

**Comment by Rasbats** [comment]
Sorry, I should have tried a rebuild. Now working. Thanks.

**Comment by leamas** [comment]
Don't be sorry, be happy. It works :)

**Comment by leamas** [comment]
BTW: Why isn't the circleci builds also done, like for appveyor and travis? Not following the project in circleci?

**Pull request merged**
