### PR TITLE
Update: cleanup,  fix for #19

### PR DESCRIPTION
**Pull request by leamas**
Here we have:

  - A fix for #19 
  - Cleanup and optimizations of the MacOS build script which now runs faster.
  - Major cleanup of the flatpak build, merging the two scripts to one, fixing a build number issue.
  - Dead code removed
  - Some typos, formatting etc. fixed.

### CODE REVIEW

**Comment by leamas** [comment]
On a sidenote: If/when you are about to merge this, please consider the Rebase option which is available when merging. It creates a much cleaner history without merge commits. Try it, you'll like it :)

**Comment by leamas** [comment]
The build error is just because the PR does not have the environment variables required to upload for security reasons. The actual build is fine.

**Comment by leamas** [comment]
Rewritten, handling debian same way as ubuntu and raspbian. Looking at the targets used today the list should be complete.

**Comment by Rasbats** [comment]
Problems on my Mac with the metadata before this commit. Trying again after the 'Rebase and merge'.

**Comment by leamas** [comment]
hm... I havn't touched the macos case. If you still have "Incompatible plugin" problems after merging this: please start opencpn on the command line using `opencpn --loglevel debug` and submit the logfile.

**Pull request merged**
