### PR TITLE
Add new Debian armhf builds, misc

### PR DESCRIPTION
**Pull request by leamas**
- Add new Bullseye and Buster armhf builds #381
  - Drop using drone.io (#217, #380)
  - Clean up build scripts after dropping Xenial
  - Fix wrong metadata in ubuntu armhf builds (was Raspbian rather than expected Ubuntu).
  - Refactor ubuntu-armhf builds to use a common script.

Closes: #381 
Closes: #217

### CODE REVIEW

**Comment by leamas** [comment]
Rebased: Cleaning up git history which was very broken.

**Comment by Rasbats** [comment]
What impact will this have when OpenCPN 5.8 comes along in March? If users upgrade will they find that existing plugins will not work on their OS? FI if running Raspbian.

**Comment by leamas** [comment]
None.

The thing is that there are no Raspbian main OpenCPN programs out there. What we distribute for use in Raspbian is Ubuntu builds. So. what we do today is using Raspbian plugins on an Ubuntu host. This only works due to a somewhat disgusting hack in OpenCPN (https://github.com/OpenCPN/OpenCPN/issues/2492). OTOH, when we now distribute Ubuntu plugins instead we have Ubuntu plugins on an Ubuntu host which of course works.

There is  a [roadmap](https://github.com/OpenCPN/OpenCPN/discussions/2502#discussioncomment-1904180) for using Debian plugins only on Debian, Ubuntu and Raspbian hosts. This is the first step on that path. It is designed to be as little disruptive as possible for users.

**Comment by Rasbats** [comment]
And if no changes have been made to plugins? 
>When all plugins have been switched to make ubuntu plugins, we just remove the runtime test which is the issue here. Practically, this could be done in next OpenCPN release, there is no rush.

https://github.com/OpenCPN/OpenCPN/issues/2492

**Comment by leamas** [comment]
A user with a Raspbian plugin (that is, those of today) will still be able to use the after next minor release 5.6.2 which is due this spring.

However after 5.8.0, perhaps in a year or so, user will have to reinstall the plugin. But that is nothing more than installing the same plugin again. Any settings saved by the old plugin will still be available.

Details in the [roadmap](https://github.com/OpenCPN/OpenCPN/discussions/2502#discussioncomment-1904180)

**Pull request merged**
