### PR TITLE
Cleanup: drop redundant code.

### PR DESCRIPTION
**Pull request by leamas**
Also cuts some time from the slow raspbian-armhf builders.

### CODE REVIEW

**Comment by leamas** [comment]
Regarding the travis build error. I can see in the log that it warns about missing  CLOUDSMITH_API_KEY.  And the same builds run fine by me, for example https://travis-ci.com/github/leamas/shipdriver_pi/builds. So, I tend to think that the variable is missing in your builder...

This PR is ready to be merged.

**Comment by Rasbats** [comment]
Using the same variable for other plugins without a problem???

**Comment by leamas** [comment]
Now, this time the travis build was aborted - perhaps when you merged? Dunno. Let's wait for next build to complete

**Comment by Rasbats** [comment]
My fault. Changed the key while the build was in progress.

**Comment by Rasbats** [comment]
Enough for tonight. Thanks again for the work on this. Hope this can be a template for other work.

**Comment by leamas** [comment]
> Enough for tonight. 
Indeed

>Thanks again for the work on this. 

Thanks, and same to you.


> Hope this can be a template for other work.

This is part of my plan. 

As for the travis errors everything is in order, it's just that the environment variables are not available to the PR for security reasons. Silly me.

Good night!

-a

**Pull request merged**
