### PR TITLE
Targets update  (#540).

### PR DESCRIPTION
**Pull request by leamas**
- Fix cmake logging of target:release 
 - Remove horrible hack for not longer used ubuntu targets
 - Update OCPN_TARGET_TUPLE for all debian targets

### CODE REVIEW

**Comment by Rasbats** [comment]
_ShipDriver-3.3.0+8957.f7d4720_debian-wx32-x86_64-11-x86_64.tar.gz_ incompatible for Jammy.

**Comment by leamas** [comment]
When you refer to jammy, you are using the PPA build, right?

**Comment by leamas** [comment]
Yep, it wont work. Log tells us `Building for target:release: debian-wx32-x86_64-x86_64:11`. This is #541 messing up things....

**Comment by Rasbats** [comment]
> When you refer to jammy, you are using the PPA build, right?

Yes.

**Pull request merged**
