### PR TITLE
ci: flatpak: Don't hardcode the manifest filename.

### PR DESCRIPTION
**Pull request by leamas**
Use a wildcard instead. Should make the file generic.

### CODE REVIEW

**Comment by leamas** [comment]
Hang on, clumsy me... will rwrite this PR. wait.

**Comment by leamas** [comment]
Now, that's better. Toke too long time to fíx, though. OK to merge from my side

**Comment by leamas** [comment]
You was a little too quick.. In the very start of circleci-build-flatpak.sh there is 

     set -e
     pwd
     ls 

Could you please remove the 'pwd' and 'ls' lines ?  These are debug junk and should be nuked.

**Comment by Rasbats** [comment]
Done.

**Pull request merged**
