### PR TITLE
Android part2

### LINKED ISSUE #258: Android Build - Logbookkonni_pi
I believe this used to build for Android
https://github.com/rgleason/LogbookKonni_pi

See this [Issue Android Failing due to wx/datactrl and  wx/timectrl  not available.](https://github.com/rgleason/LogbookKonni_pi/issues/42)

Sean has two files that solve this wxWidgets issue. I will try to find them.

### PR DESCRIPTION
**Pull request by leamas**
This builds. And I  think I have got the right structure. 

In current state, it builds successfully  on circleci. More important, with the Android NDK installed it also supports local Android builds without using docker. I see no reason why this should not be possible also on Windows, although it's only tested on  Linux. 

The basic building blocks:
  - Proper cmake toolchain files for armhf and aarch64
  - Updated cmake version in the ci builds to be able to cope with the NDK toolchain.
  - A new plugingl library
  - And, important, updated INSTALL.md describing Android builds. 

I suggest that we close #258  after merging this. Of course, there will be new bugs. But it's then better to file new issues rather than just continuing in the old jack-of-all-trades 258.

Closes: #258

### CODE REVIEW

**Comment by Rasbats** [comment]
Fantastic. Small thing but it makes a huge difference. ShipDriver dialog now responds to mouseevents on Android!
This was quite a barrier for using the plugin on Android.
Many thanks.

**Comment by leamas** [comment]
Thanks. 

"small thing" might mean different things. In this case, it was certainly some hours at the keyboard. OTOH, some of those hours were indeed spent on making the code smaller :)

**Comment by Rasbats** [comment]
Sorry ... small thing for the user.

**Comment by leamas** [comment]
Those things are the best, no doubt.

**Pull request merged**
