### PR TITLE
debian upload: Don't use updated urllib3 libary

### PR DESCRIPTION
**Pull request by leamas**
The cloudsmith pythonpackage is incompatible with version 2.0.0 of urllib3, released end of April. Lock urllib2 to be < 2.0.0 until cloudsmith has updated their package

Closes: #520

### CODE REVIEW

**Comment by Rasbats** [comment]
Thanks again.

**Comment by leamas** [comment]
oops.. my bad: This PR contained also an update to opencpn-libs.

It's master, we can live with it. Still a need to update the Changelog

**Comment by Rasbats** [comment]
Could you cherry pick the urllib bit to v3.2 (other bits?)? I can then make a sd3.2.4-beta2 for some more plugin updates.

**Comment by leamas** [comment]
I'm on it, but let's  clean up master first... stay tuned

**Comment by leamas** [comment]
I am confused. This PR is merged, but it is not visible in the history. Have you any idea what's going on?

**Comment by Rasbats** [comment]
>I am confused

Me too. The merge has gone into branch v3.2 and not master.

**Comment by leamas** [comment]
Ok... something happened when you merged.

Lessons learned: look a little more carefully on the PR. In the top you can see the branch which will be updated.

Lessons learned #2: I need to check my PRs better.

I'll make a new PR for master

**Pull request merged**
