### PR TITLE
Ci fixes

### PR DESCRIPTION
**Pull request by leamas**
OK, here is last part: the setup which uploads build artifacts to cloudsmith repos. Again, there are some details in CI.md which is part of this PR.

### CODE REVIEW

**Comment by leamas** [comment]
The build failure is OK - it's about missing environment setup (see CI.md).

**Comment by Rasbats** [comment]
I am normally using the CloudSmith Environment Variable in Travis. Will this work?

**Comment by leamas** [comment]
Not really sure what you mean... did you take a look into CI.md?

**Comment by Rasbats** [comment]
Previously I had added a github repository to Travis and used the CloudSmith API key to allow access. At the moment I am getting an error from Travis. Is it because I deleted the other environment variables I found on Travis?

**Comment by leamas** [comment]
hm... what is the error?

**Comment by Rasbats** [comment]
Finally Travis has allowed me to include ShipDriver. Had to sign out and back in. Now how to remake this pull request.

**Comment by Rasbats** [comment]
Ok, I am re-running the build.

**Comment by leamas** [comment]
You can rebuild the commit on circleci and appveyor as well, both have options to trigger a build manually IIRC. Unfortunately, the travis build is the slowest one by some margin (10 min +)

**Comment by leamas** [comment]
Nope, it's still not OK. However, I'm not really sure how the PR builds are run -- do they have the environment? dunno.

That said, the error is in the end of the build log: 

```
$  cd build; bash < upload.sh

+python3 -m cloudsmith_cli push raw --no-wait-for-sync --name ShipDriver-raspbian-9.4-metadata --version 2.4+40.cb4510b --summary 'Plugin metadata for automatic installation' david-register/ocpn-plugins-unstable ShipDriver-raspbian-9.4.xml

Checking raw package upload parameters ... -ERROR

Failed to validate upload parameters! (status: 401 - Unauthorized)

Detail: Authentication credentials were not provided.

Hint: You don't have an API key set, but it seems this action requires authentication - Try getting your API key via 'cloudsmith token' first then try again.

The command "cd build; bash < upload.sh" exited with 145.

Done. Your build exited with 1.
```

Here are two errors. The _Detail: Authentication credentials were not provided._ means, as I understand it, that CLOUDSMITH_API_KEY is not set. And the repo name is wrong, indicating that CLOUDSMITH_UNSTABLE_REPO is not set to the name of your Cloudsmith repo (david-register/... is the default value).

**Comment by Rasbats** [comment]
I have not set up the repos on CloudSmith yet. Another job to do first.

**Comment by leamas** [comment]
Right. Besides that, the build actually looks fine. Which means that the .deb package, the tarball and the metadata file are created without build failures.

It might be an advantage to startup the  circleci and appveyor builders before dealing with cloudsmith. They all build faster, which means quicker turn-around  times. And after all, it should be done anyway. Just let them fail in the upload script as a starter

**Comment by Rasbats** [comment]
All built, including MacOSX. But... does not seem to find all the metadata in the tarball and does not allow import. I will now take a look at the tarball.

**Comment by Rasbats** [comment]
My repos are here, including Flatpak:[https://cloudsmith.io/~mike-rossiter/repos/shipdriver-prod/packages/](url)

**Comment by leamas** [comment]
Could you attach the tarball here so I can have  a look as well?

**Comment by Rasbats** [comment]
[ShipDriver-2.4+7.v2.4.4_msvc-10.0.14393-win32.tar.gz](https://github.com/Rasbats/shipdriver_pi/files/5124182/ShipDriver-2.4%2B7.v2.4.4_msvc-10.0.14393-win32.tar.gz)

**Comment by Rasbats** [comment]
Is that + sign a problem?

**Comment by leamas** [comment]
Shouldn't be. Be the contents is weird. Let me do dome local checks here,...

**Comment by Rasbats** [comment]
Here is the problem, I think:
<target-arch>x86_64</target-arch> normally.
 <target-arch>i386</target-arch> in this version.

**Comment by leamas** [comment]
Another problem is that somewhere in the rebasing I did the metadata file is in the wrong location.  I'll submit a patch for this.

> Here is the problem, I think:
> x86_64 normally.
> i386 in this version.

Where is it i386?

**Comment by Rasbats** [comment]
<target-arch>i386</target-arch>
On Windows at this end.

**Comment by Rasbats** [comment]
Could you do a PR please.

**Comment by Rasbats** [comment]
Many thanks. I am on the case. Let you know when I have some results.

**Comment by leamas** [comment]
OK, back to the arch. The simple thing is that opencpn is a 32-bit application, so using i386 on windows is correct. OTOH, it's kind of messed up. All plugins today are using x86_64, even the windows ones. We need to file a bug against OpenCPN, and learn to live with this mess for some time. I'll be back...

**Comment by leamas** [comment]
So, if everyone makes the same error... I should have been more active in the beta phase. Sigh. 

Anyway, you have a PR.  Building on 8 platforms...

**Comment by Rasbats** [comment]
Sorry... The metadata xml file seems to have gone to the wrong folder:
[ShipDriver-2.4+11.v2.4.5_msvc-10.0.14393-win32.tar.gz](https://github.com/Rasbats/shipdriver_pi/files/5124496/ShipDriver-2.4%2B11.v2.4.5_msvc-10.0.14393-win32.tar.gz)

**Comment by leamas** [comment]
Anyway, found some rebasing relics. Now it should definitely be better...

**Comment by leamas** [comment]
Please drop #15, #16 contains it.

**Comment by leamas** [comment]
Regarding https://github.com/Rasbats/shipdriver_pi/pull/13#issuecomment-680081985: Now the structure looks sane, but it's still the correct value i386 which should be x86_64

**Comment by Rasbats** [comment]
'Requesting file upload for ShipDriver-2.4+41.v2.4.6_ubuntu-18.04-x86_64.tar.gz'
This is from the build for 'bionic'. My other stuff uses 'bionic.tar.gz'. Is there a typo somewhere?

**Comment by leamas** [comment]
> ShipDriver-2.4+41.v2.4.6_ubuntu-18.04-x86_64.tar.gz... typo?

First, this just a filename and will work nevertheless. However, this is the correct form:` <name>-<version>_<target os>-<target os version>-<arch>`. 

There are reasons to use numeric id's for target os versions so they can be sorted. 

Jon wants to have the build os in the filename. This is fine, besides that it is build info which is after the + (using semantic versioning).

**Comment by leamas** [comment]
When I check at the tarballs at your repo the look sane. And you?

**Comment by leamas** [comment]
Nope, not sane. Still i386 on msvc builds. I'll be back

**Comment by Rasbats** [comment]
Same incorrect location of the metadata xml for Bionic.

**Comment by leamas** [comment]
hm... strange. I build the same bionic, getting the metadata in correct location. The diff is #16 i. e.,

    diff --git a/cmake/GetArch.cmake b/cmake/GetArch.cmake
    index 885dc08..8fb8c65 100644
    --- a/cmake/GetArch.cmake
    +++ b/cmake/GetArch.cmake
    @@ -30,7 +30,7 @@ function(GetArch)
       else (NOT WIN32)
         # Should really be i386 since we are on win32. However, it's
         # x86_64 for now, see #2027
    -    set (ARCH "i386")
    +    set (ARCH "x86_64")
       endif (NOT WIN32)
       set (ARCH ${ARCH} PARENT_SCOPE)
     endfunction(GetArch)
    diff --git a/cmake/metadata.cmake b/cmake/metadata.cmake
    index 72f6808..90d47d1 100644
    --- a/cmake/metadata.cmake
    +++ b/cmake/metadata.cmake
    @@ -90,6 +90,7 @@ set(repack_tarball_script
     tmpdir=repack.$$
     rm -rf $tmpdir && mkdir $tmpdir
     tar -C $tmpdir -xf $1
    +rm -rf $tmpdir/root
     cp $2 $tmpdir/*/
     tar -C $tmpdir -czf $1 .
     rm -rf $tmpdir

Just to make it sane, what if you merge #16? That should give the same result as for me at https://cloudsmith.io/~alec-leamas/repos/opencpn-plugins-unstable/packages/detail/raw/ShipDriver-ubuntu-18.04-tarball/2.4+333.ea2a21c/

**Comment by Rasbats** [comment]
Did #16 an hour ago just merging #17.

**Comment by leamas** [comment]
Sorry. my bad. Anyway, our separate branches are identical. Let's see if we get different results in cloudsmith, which would be sort of interesting...

**Comment by leamas** [comment]
New bionic build looks fine at your repo...

**Comment by Rasbats** [comment]
Still looks wrong on MSVC. And still wrong place for my Bionic. Have you tried installing the Bionic build? Off to watch the news!

**Comment by leamas** [comment]
Ack - I see the error. "blushes" Heck, I wrote that spec, but didn't read it. Thought I remembered, I guess... Please stay tuned

**Pull request merged**
