### PR TITLE
Local build: clean up and bugfixes.

### PR DESCRIPTION
**Pull request by leamas**
Added documentation, see https://github.com/Rasbats/managed_plugins/pull/18

Fixed a number of bugs, partly due to insuffient testing on Windows, partly since two of my earlier PR broke when they were combined, partly to enhance on-line docs. Nothing here should be controversial

### CODE REVIEW

**Comment by leamas** [comment]
please don't merge. Finding more bugs...

**Comment by Rasbats** [comment]
Merged by mistake.

**Comment by Rasbats** [comment]
Now reverted ... I hope.

**Comment by Rasbats** [comment]
circleci has given up on me. Not just this plugin but also JavaScript_pi.

**Comment by leamas** [comment]
So far here is nothing which affects the circleci builds, only the local ones. If you have have problems, it's something else.

**Comment by Rasbats** [comment]
Things have started working again. Nothing changed.

**Comment by Rasbats** [comment]
Left with a problem following commit a6e0643. The Raspbian bullseye fails.
Build is here:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/654/workflows/b7c8f5d2-5e9d-4219-95b5-7c9468bb5213/jobs/5109](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/654/workflows/b7c8f5d2-5e9d-4219-95b5-7c9468bb5213/jobs/5109
)
Could you take a look when time allows? Bit of a mess at the moment.

**Pull request merged**
