### PR TITLE
Enable Ubuntu 22.04 (Jammy) build

### PR DESCRIPTION
**Pull request by bdbcat**

### CODE REVIEW

**Comment by leamas** [comment]
This PR does not hurt, and is actually helpful when doing local builds. However, for the main CI builds it does not affect anything since we  hardcode the target using -DOCPN_TARGET_TUPLE in _.circleci/config.yml_ in those. This basically overrides these changes.

However, we should not let these debug statements linger in the code, they only messes up the output. We already do log the effective target tuple.

**Comment by Rasbats** [comment]
So why was a previous ci build _ShipDriver-3.3.0+55.03d4441_debian-wx32-11-x86_64.tar.gz_ found to be incompatible?

**Comment by leamas** [comment]
It shouldn't. Have you got a build log?

**Comment by leamas** [comment]
... and a build log for the last, working one?

**Comment by Rasbats** [comment]
Last working one:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/970/workflows/e574f473-b0b8-40cb-86c0-966dad8f3a0d]( https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/970/workflows/e574f473-b0b8-40cb-86c0-966dad8f3a0d)

And the previous beta3 for the beta catalog that was incompatible:
[https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/966/workflows/3153aa3e-73d3-4cdd-8c09-8e7e0696e520](https://app.circleci.com/pipelines/github/Rasbats/shipdriver_pi/966/workflows/3153aa3e-73d3-4cdd-8c09-8e7e0696e520)

**Comment by leamas** [comment]
Thanks. This smells, need to clean up things. please stay tuned, it might take a while...

**Comment by leamas** [comment]
See #540, let's continue there.

**Pull request merged**
