### PR TITLE
Flatpak fixes

### PR DESCRIPTION
**Pull request by leamas**
After trying the workflows, a revision: Keep the existing circleci flatpak builder which builds for x86_64/18.08. And use the new github builders only for builds against the beta branch i. e., aarch64/x86_64/20.08. It's a pity to add more build minutes to circleci, but this means the currently used x86_64/18.08 is built in a safe environment. It also means we have x86_64/20.08 beta plugins we can test besides the aarch64.

Things are moving. Got an invitation to test circleci's upcoming Arm builders. No idea what this means, but I pushed the button.  Perhaps it isn't that long before we have better solution than my builder at home (actually, at my work, don't tell anyone...)

Most stuff here is about cleaning up branches and  runtime version. There is a related issue https://github.com/OpenCPN/OpenCPN/issues/2181 at opencpn.

### CODE REVIEW

**Comment by Rasbats** [comment]
My RPi 4 should be up and running tomorrow. In the meantime I am fighting issues with PhotoLayer. It seems to build for Linux but none of those plugins work. Linked to Proj and the need for the static lib sqlite3 when building.

**Comment by leamas** [comment]
OK... file a bug against photolayer and drop me a note. In the bug, please  link to the build logs.

**Comment by Rasbats** [comment]
Messed around a lot with PhotoLayer and may have broken something. Do you have a recent repo I could copy? I could not find anything at github/leamas.

**Comment by leamas** [comment]
Havn't you got the git history?

**Comment by Rasbats** [comment]
Yes, I have and I tried to use this. It built on CircleCI but the plugins did not work. Now building locally to test. I will move this conversation to PhotoLayer - [https://github.com/Rasbats/photolayer_pi/issues/34](https://github.com/Rasbats/photolayer_pi/issues/34)

**Pull request merged**
